import React from 'react';
import { DispatchAction } from '../types/energy';
import { CheckCircle2, AlertTriangle, ShieldCheck, Clock, Cpu, ToggleLeft, ToggleRight, Zap } from 'lucide-react';

interface IndustrialDispatchConsoleProps {
  actions: DispatchAction[];
  onApproveAction: (id: string) => void;
  autoPilot: boolean;
  onToggleAutoPilot: () => void;
}

export const IndustrialDispatchConsole: React.FC<IndustrialDispatchConsoleProps> = ({
  actions,
  onApproveAction,
  autoPilot,
  onToggleAutoPilot
}) => {
  return (
    <div className="console-panel p-4 rounded-sm">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-800 pb-3 mb-4 gap-3">
        <div>
          <div className="flex items-center space-x-2">
            <Cpu className="w-4 h-4 text-cyan-400" />
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-100">
              Orchestration Dispatch Actions & Load Shift Console
            </h3>
          </div>
          <p className="text-[11px] text-slate-400 font-mono mt-0.5">
            Automated control signals & actionable recommendations generated by Predictive Engine
          </p>
        </div>

        {/* Auto-Pilot Closed-Loop Switch */}
        <div className="flex items-center space-x-3 bg-slate-950 px-3 py-1.5 rounded border border-slate-800 text-xs font-mono">
          <div className="flex flex-col">
            <span className="text-[10px] text-slate-400 uppercase">Dispatch Control Mode:</span>
            <span className={`font-semibold ${autoPilot ? 'text-emerald-400' : 'text-amber-400'}`}>
              {autoPilot ? 'Autonomous Closed-Loop' : 'Manual Operator Confirmation'}
            </span>
          </div>

          <button
            onClick={onToggleAutoPilot}
            className={`flex items-center space-x-1 px-2 py-1 rounded transition-colors ${
              autoPilot
                ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                : 'bg-slate-900 text-slate-300 border border-slate-700'
            }`}
            title="Toggle Closed-Loop Autonomous Execution"
          >
            {autoPilot ? (
              <ToggleRight className="w-5 h-5 text-emerald-400" />
            ) : (
              <ToggleLeft className="w-5 h-5 text-slate-400" />
            )}
            <span className="text-[11px]">{autoPilot ? 'AUTOPILOT ON' : 'MANUAL'}</span>
          </button>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left font-mono text-xs">
          <thead>
            <tr className="border-b border-slate-800 text-slate-400 text-[11px] uppercase tracking-wider bg-slate-950/60">
              <th className="py-2.5 px-3">Severity</th>
              <th className="py-2.5 px-3">Dispatch Source</th>
              <th className="py-2.5 px-3">Action Title & Technical Detail</th>
              <th className="py-2.5 px-3">Timing Window</th>
              <th className="py-2.5 px-3">Financial Impact</th>
              <th className="py-2.5 px-3">Row Status</th>
              <th className="py-2.5 px-3 text-right">Operator Control</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800 text-slate-200">
            {actions.map((act) => {
              const isAppliedAuto = act.status === 'Applied Automatically';
              const isVerified = act.status === 'Applied (Operator Verified)';
              const isPending = act.status === 'Pending Verification';

              return (
                <tr
                  key={act.id}
                  className={`transition-colors ${
                    isVerified
                      ? 'bg-emerald-950/20'
                      : isAppliedAuto
                      ? 'bg-slate-900/40'
                      : 'hover:bg-slate-850/50'
                  }`}
                >
                  
                  {/* Severity Badge */}
                  <td className="py-3 px-3">
                    <span className={`inline-block text-[10px] font-mono uppercase px-2 py-0.5 rounded border ${
                      act.severity === 'critical'
                        ? 'bg-rose-950/80 text-rose-300 border-rose-800'
                        : act.severity === 'advisory'
                        ? 'bg-amber-950/80 text-amber-300 border-amber-800'
                        : 'bg-slate-800 text-slate-300 border-slate-700'
                    }`}>
                      {act.severity}
                    </span>
                  </td>

                  {/* Dispatch Source */}
                  <td className="py-3 px-3 font-semibold text-slate-300">
                    {act.source}
                  </td>

                  {/* Title & Detail */}
                  <td className="py-3 px-3 max-w-xs">
                    <div className="font-semibold text-slate-100 flex items-center gap-1.5">
                      {isVerified && <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 animate-pulse" />}
                      <span>{act.title}</span>
                    </div>
                    <div className="text-[11px] text-slate-400 font-sans mt-0.5 leading-snug">
                      {act.detail}
                    </div>
                  </td>

                  {/* Timing Window */}
                  <td className="py-3 px-3 text-slate-300">
                    <div className="flex items-center space-x-1 text-slate-400">
                      <Clock className="w-3 h-3 text-slate-400" />
                      <span>{act.timing}</span>
                    </div>
                  </td>

                  {/* Financial Impact */}
                  <td className="py-3 px-3 font-semibold text-emerald-400">
                    {act.financialImpact}
                  </td>

                  {/* Row Status Badge */}
                  <td className="py-3 px-3">
                    <span className={`inline-flex items-center gap-1.5 text-[10px] font-mono px-2 py-0.5 rounded border ${
                      isVerified
                        ? 'bg-emerald-950 text-emerald-400 border-emerald-700 font-bold'
                        : isAppliedAuto
                        ? 'bg-cyan-950 text-cyan-300 border-cyan-800'
                        : 'bg-amber-950 text-amber-300 border-amber-800'
                    }`}>
                      {isVerified ? (
                        <CheckCircle2 className="w-3 h-3 text-emerald-400 animate-bounce" />
                      ) : isAppliedAuto ? (
                        <ShieldCheck className="w-3 h-3 text-cyan-400" />
                      ) : (
                        <AlertTriangle className="w-3 h-3 text-amber-400" />
                      )}
                      <span>{act.status}</span>
                    </span>
                  </td>

                  {/* Operator Control Button */}
                  <td className="py-3 px-3 text-right">
                    {isPending ? (
                      <button
                        onClick={() => onApproveAction(act.id)}
                        className="px-3 py-1.5 rounded bg-emerald-950 hover:bg-emerald-900 text-emerald-300 border border-emerald-700 text-[11px] font-mono transition-all flex items-center gap-1 ml-auto shadow-sm shadow-emerald-950"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        <span>Verify & Dispatch</span>
                      </button>
                    ) : isVerified ? (
                      <span className="text-emerald-400 text-[11px] font-mono flex items-center justify-end gap-1 font-semibold">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> Applied
                      </span>
                    ) : (
                      <span className="text-slate-500 text-[11px] font-mono">Closed-Loop</span>
                    )}
                  </td>

                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};
