import React from 'react';
import { DispatchAction } from '../types/energy';
import { CheckCircle2, AlertTriangle, ShieldCheck, Clock, Cpu, ToggleLeft, ToggleRight } from 'lucide-react';

interface IndustrialDispatchConsoleProps {
  actions: DispatchAction[];
  onApproveAction: (id: string) => void;
  autoPilot: boolean;
  onToggleAutoPilot: () => void;
}

export const IndustrialDispatchConsole: React.FC<IndustrialDispatchConsoleProps> = ({
  actions,
  onApproveAction,
  autoPilot,
  onToggleAutoPilot
}) => {
  return (
    <div className="bg-[#131B2E]/70 border border-slate-700/50 rounded-xl p-5 shadow-sm">
      
      {/* Table Header & Auto-Pilot Toggle */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-800 pb-4 mb-4 gap-3">
        <div>
          <div className="flex items-center space-x-2">
            <Cpu className="w-4 h-4 text-sky-400" />
            <h3 className="text-sm font-sans font-bold text-slate-100">
              Orchestration Dispatch Actions & Load Shift Console
            </h3>
          </div>
          <p className="text-xs text-slate-400 font-sans mt-0.5">
            Automated recommendations and control signals generated by the Predictive Engine
          </p>
        </div>

        {/* Auto-Pilot Switch */}
        <div className="flex items-center space-x-3 bg-slate-900/90 px-3.5 py-1.5 rounded-lg border border-slate-800 text-xs font-sans">
          <div className="flex flex-col">
            <span className="text-[11px] text-slate-400">Dispatch Mode:</span>
            <span className={`font-semibold ${autoPilot ? 'text-emerald-400' : 'text-amber-400'}`}>
              {autoPilot ? 'Autonomous Closed-Loop' : 'Manual Operator Confirmation'}
            </span>
          </div>

          <button
            onClick={onToggleAutoPilot}
            className={`flex items-center space-x-1.5 px-2.5 py-1 rounded-md transition-all ${
              autoPilot
                ? 'bg-emerald-950/80 text-emerald-300 border border-emerald-800/80 font-medium'
                : 'bg-slate-800 text-slate-300 border border-slate-700/80'
            }`}
            title="Toggle Closed-Loop Autonomous Dispatch Mode"
          >
            {autoPilot ? (
              <ToggleRight className="w-5 h-5 text-emerald-400" />
            ) : (
              <ToggleLeft className="w-5 h-5 text-slate-400" />
            )}
            <span className="text-xs">{autoPilot ? 'Autopilot On' : 'Manual'}</span>
          </button>
        </div>
      </div>

      {/* High-density Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-left font-sans text-xs">
          <thead>
            <tr className="border-b border-slate-800 text-slate-400 text-xs font-medium uppercase bg-slate-900/50">
              <th className="py-2.5 px-3">Severity</th>
              <th className="py-2.5 px-3">Source</th>
              <th className="py-2.5 px-3">Action Description & Detail</th>
              <th className="py-2.5 px-3">Timing</th>
              <th className="py-2.5 px-3">Financial Impact</th>
              <th className="py-2.5 px-3">Status</th>
              <th className="py-2.5 px-3 text-right">Human Control</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60 text-slate-200">
            {actions.map((act) => {
              const isAppliedAuto = act.status === 'Applied Automatically';
              const isVerified = act.status === 'Applied (Operator Verified)';
              const isPending = act.status === 'Pending Verification';

              return (
                <tr
                  key={act.id}
                  className={`transition-colors ${
                    isVerified
                      ? 'bg-emerald-950/20'
                      : isAppliedAuto
                      ? 'bg-slate-900/30'
                      : 'hover:bg-slate-800/40'
                  }`}
                >
                  
                  {/* Severity Badge */}
                  <td className="py-3 px-3">
                    <span className={`inline-block text-[11px] font-sans px-2 py-0.5 rounded-full border ${
                      act.severity === 'critical'
                        ? 'bg-rose-950/80 text-rose-300 border-rose-800/60 font-medium'
                        : act.severity === 'advisory'
                        ? 'bg-amber-950/80 text-amber-300 border-amber-800/60 font-medium'
                        : 'bg-slate-800 text-slate-300 border-slate-700/60'
                    }`}>
                      {act.severity.charAt(0).toUpperCase() + act.severity.slice(1)}
                    </span>
                  </td>

                  {/* Dispatch Source */}
                  <td className="py-3 px-3 font-medium text-slate-300">
                    {act.source}
                  </td>

                  {/* Title & Detail */}
                  <td className="py-3 px-3 max-w-sm">
                    <div className="font-semibold text-slate-100 flex items-center gap-1.5">
                      {isVerified && <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />}
                      <span>{act.title}</span>
                    </div>
                    <div className="text-xs text-slate-400 mt-0.5 leading-snug">
                      {act.detail}
                    </div>
                  </td>

                  {/* Timing Window */}
                  <td className="py-3 px-3 text-slate-300">
                    <div className="flex items-center space-x-1.5 text-slate-400">
                      <Clock className="w-3.5 h-3.5 text-slate-400" />
                      <span>{act.timing}</span>
                    </div>
                  </td>

                  {/* Financial Impact */}
                  <td className="py-3 px-3 font-semibold text-emerald-400 font-mono">
                    {act.financialImpact}
                  </td>

                  {/* Status Badge */}
                  <td className="py-3 px-3">
                    <span className={`inline-flex items-center gap-1.5 text-[11px] font-sans px-2 py-0.5 rounded-full border ${
                      isVerified
                        ? 'bg-emerald-950/80 text-emerald-300 border-emerald-800/80 font-medium'
                        : isAppliedAuto
                        ? 'bg-sky-950/80 text-sky-300 border-sky-800/80 font-medium'
                        : 'bg-amber-950/80 text-amber-300 border-amber-800/80 font-medium'
                    }`}>
                      {isVerified ? (
                        <CheckCircle2 className="w-3 h-3 text-emerald-400" />
                      ) : isAppliedAuto ? (
                        <ShieldCheck className="w-3 h-3 text-sky-400" />
                      ) : (
                        <AlertTriangle className="w-3 h-3 text-amber-400" />
                      )}
                      <span>{act.status}</span>
                    </span>
                  </td>

                  {/* Neat Action Button with subtle green border */}
                  <td className="py-3 px-3 text-right">
                    {isPending ? (
                      <button
                        onClick={() => onApproveAction(act.id)}
                        className="px-3 py-1.5 rounded-md bg-emerald-950/80 hover:bg-emerald-900 text-emerald-300 border border-emerald-700/80 text-xs font-medium transition-all flex items-center gap-1.5 ml-auto shadow-sm"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        <span>Confirm Dispatch</span>
                      </button>
                    ) : isVerified ? (
                      <span className="text-emerald-400 text-xs font-medium flex items-center justify-end gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> Confirmed
                      </span>
                    ) : (
                      <span className="text-slate-400 text-xs">Autonomous</span>
                    )}
                  </td>

                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};
